---
- hosts: localhost
  connection: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Check swap State
      ansible.builtin.stat:
        path: /swapfile
      register: swap_file_check
    - name: Umount swap | {{ inventory_hostname }}
      ansible.posix.mount:
        name: swap
        fstype: swap
        state: absent
      when: swap_file_check.stat.exists
    - name: Swap Off | {{ inventory_hostname }}
      ansible.builtin.shell:
        cmd: swapoff -a
      when: ansible_swaptotal_mb > 0
    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Hashicorp GPG key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present
        update_cache: false
    - name: Add Hashicorp repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
        state: present
        update_cache: false
    - name: Install Packages
      ansible.builtin.apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - vagrant
          - terraform
          - nomad
          - vault
          - docker-ce
          - ksmtuned
          - packer
          - zsh
          - libvirt-clients
          - libxslt-dev
          - libxml2-dev
          - libvirt-dev
          - zlib1g-dev
          - ruby-dev
          - ruby-libvirt
          - ebtables
          - keyboard-configuration
          - console-setup
          - language-pack-fr
        update_cache: true
      tags: packages
    - name: Change local to FR
      community.general.locale_gen:
        name: fr_FR.UTF-8
        state: present
      tags: local
    - name: configure keyboard
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "/etc/default/{{ item }}"
        force: yes
        owner: root
        group: root
        mode: 0640
      loop:
        - keyboard
        - locale
      notify:
        - dpkg-reconfigure
      tags: keyboard
    - name: Add vagrant to groups
      ansible.builtin.user:
        shell: /usr/bin/zsh
        name: vagrant
        groups: docker,libvirt
        append: yes
    - name: Get arkade
      ansible.builtin.shell: curl -SLfs https://get.arkade.dev | sudo sh
      become: false
    - name: Check swap State
      ansible.builtin.stat:
        path: /home/vagrant/.oh-my-zsh
      register: ohmyzsh_file_check
    - name: Get Oh my zsh
      become: false
      ansible.builtin.shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
      tags: zsh
      when: not ohmyzsh_file_check.stat.exists
    - name: tools with arkade get
      ansible.builtin.shell: ark get "{{item}}"
      loop:
        - buildx
        - docker-compose
        - helm
        - kubectl
        - hugo
        - jq
        - k9s
        - kail
        - kind
        - krew
        - kubectx
        - kubens
        - kustomize
        - minikube
        - popeye
        - polaris
        - stern
        - tfsec
        - trivy
        - yq
      become: false
    - name: uncomment PATH
      ansible.builtin.lineinfile:
        path: /home/vagrant/.zshrc
        regexp: '^# export PATH.*$'
        line: 'export PATH=$HOME/.arkade/bin:$HOME/.local/bin:$PATH'
      become: false
      tags: path
    - name: add PATH
      ansible.builtin.lineinfile:
        path: /home/vagrant/.zshrc
        state: present
        regexp: '^# export (PATH=\")({{ item }}:)?((?(2).*?(?!(?:.\"))|.*?(?!(?:{{ item }}))))(:{{ item }})?((?(4).*|\"))'
        line: '\1\3:{{ item }}\5'
        backrefs: yes
      loop:
        - "$HOME/.arkade/bin"
        - "$HOME/.local/bin"
      tags: path
      become: false
    - name: Install pip packages
      ansible.builtin.pip:
        requirements: /home/vagrant/my-vagrant-box/requirements.yml
      become: false
      tags: pip
    - name: Install vagrant plugin libvirt
      ansible.builtin.shell: vagrant plugin install vagrant-libvirt
      become: false
      tags: vagrant
    - name: Install hadolint
      ansible.builtin.uri:
        url: https://github.com/hadolint/hadolint/releases/download/v2.8.0/hadolint-Linux-x86_64
        dest: /home/vagrant/.local/bin/hadolint
        mode: 0755
        owner: vagrant
        group: vagrant
        status_code: [200,304]
      tags: hadolint
    - name: Install regula
      ansible.builtin.shell: wget https://github.com/fugue/regula/releases/download/v2.2.0/regula_2.2.0_Linux_x86_64.tar.gz -O - | sudo tar -xz -C /usr/local/bin
      tags: regula
    - name: install Azure cli
      ansible.builtin.shell: curl -sL https://aka.ms/InstallAzureCLIDeb | bash

  handlers:
    - name: dpkg-reconfigure
      shell: |
        dpkg-reconfigure -f noninteractive keyboard-configuration && \
        localectl set-locale LANG=fr_FR.UTF8 LANGUAGE=fr_FR.UTF8 && \
        timedatectl set-timezone Europe/Paris && \
        update-locale LANG=fr_FR.UTF-8

